# Generated by Django 5.0.7 on 2024-11-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_delivery_period_order_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveBigIntegerField(default=1, null=True),
        ),
    ]
