# Generated by Django 5.0.7 on 2024-11-30 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='user',
        ),
    ]
